### ISSUE TITLE
Bumblebee-nvidia fails to build nvidia blob

### ISSUE THREAD

**Issue by mex20** [Bumblebee-Project/Bumblebee#856]
Hello,

     I have been trying to get bumblebee to work with a 15" mid 2010 macbook pro 6,2 that has a Core I7-m620, an IronLake iGPU, and a NVIDIA Corporation GT216M [GeForce GT 330M] (rev a2) and have had some trouble getting it to work.

After following the installation instructions from the fedora project site for the closed source unmanaged with proprietary nvidia blob, my system does not want to boot into the GUI. It takes a few minutes, but eventually a login prompt appears and I have been able to run 'sudo bumblebee-nvidia --debug' command and I get the text in the file below:
[bumblebee-nvidiadebug.txt](https://github.com/Bumblebee-Project/Bumblebee/files/863228/bumblebee-nvidiadebug.txt)

**Comment by gsgatlin** [comment]
Interesting. Ok. Try this:

copy the bumblebee-nvidia script to somewhere. Like in your home directory.

cp /usr/sbin/bumblebee-nvidia ./

edit with some text editor.

find the line:

bumblebee_libglvnd="--no-libglx-indirect --no-install-libglvnd --no-glvnd-glx-client --no-glvnd-egl-client"

and change it to:

bumblebee_libglvnd=""

save that. Then run it with root or sudo. Does that temporarily work around the issue? If so I think we can maybe fix it permanently by querying the installer's help function. Just want to see if that even works though.

**Comment by mex20** [comment]
I just got done trying your suggestion. It was successful in it's purpose of letting the nvidia-installer run successfully. Now I am just getting stuck with the nvidia.ko not loading. 

Thank you very much for your help on this.

**Comment by gsgatlin** [comment]
hmnn. I might have access to a macbook with nvidia. Not really sure though about that. But in any event, can you post the log of

/var/log/nvidia-installer.log 

to

https://paste.fedoraproject.org/

and post the link in this issue. Do you know if anyone got bumblebee to work on a macbook with any distros? I think bbswitch doesn't work on a macbook. But there is a different module iirc.

**Comment by gsgatlin** [comment]
Yeah, this was it.

https://github.com/ah-/gmux-scripts

https://github.com/ah-/gmux

so somehow you'd have to get that to work with fedora. Looks like it was made for ubuntu. and it looks kind of old.

**Comment by mex20** [comment]
[Here](https://paste.fedoraproject.org/paste/AXas6hUdEFKPf6PdgGhkr15M1UNdIGYhyRLivL9gydE=) is the log out of the /var/log/nvidia-installer.log as requested. To me it looks like the nouveau driver was still running and stopping the Nvidia driver from being loaded. I am pretty sure that the nouveau driver is running from what I can see using lsmod and [modinfo nouveau.](https://paste.fedoraproject.org/paste/3-vIWp5cV8eKwGG9XFrZ5V5M1UNdIGYhyRLivL9gydE=)

Thanks for the links to the other project to help me out. I am curious as to why you think that bbswitch doesnt work on a macbook, and if it doesnt then I would love to help get it running if possible. I have only discovered this project 3 days ago and have yet to dive deep into the code.

**Comment by gsgatlin** [comment]
Hello.

I mentioned bbswitch due to:

https://github.com/Bumblebee-Project/Bumblebee/issues/585

https://docs.google.com/document/d/1Nz0fhczdFHBWnSv1Wr3BWOflU-1AvIwNvjVYfeHfT94/edit

So far I have not been able to install fedora 25 on a 2012 macbook pro I have access to. If I use a external DVD drive it hangs on waiting for boot process to start forever and the live desktop never starts.

If I use livecd-iso-to-disk utility the usb disk will not even boot when I press "option" key fedora does not even show up as a option to boot from.

So if I have a fresh macbook pro how can I even install fedora on it to test out bumblebee? It seems like extremely disagreeable hardware to install fedora to.

**Comment by gsgatlin** [comment]
Ok. It seems MAC boot system thinks fedora usb disk should be labeled "Windows". Trying to install now. But there are LOTs of issues.

**Comment by gsgatlin** [comment]
"sda may not have enough space for grub2 to embed core.img using the ext4 file system on partition"

So it seems I cannot get past that. :(

**Comment by dje4321** [comment]
[nvidia-installer.log.txt](https://github.com/Bumblebee-Project/Bumblebee/files/931590/nvidia-installer.log.txt)

here is my install log. I get the same error when it trys to compile

**Comment by gsgatlin** [comment]
@dje4321 Nvidia out of tree driver module doesn't support 4.11 kernel yet. (Or even 4.10)

I found a patch for 4.10 but did not find one for 4.11 kernel. Did anyone else find one?
https://devtalk.nvidia.com/default/topic/995636/-patches-378-13-4-10-and-4-11-stageing/

**Comment by dje4321** [comment]
@gsgatlin that is strange. the 4.10 kernel worked fine for me in fedora 25. 
Would downgrading the kernel let me compile the driver?

**Comment by gsgatlin** [comment]
@dje4321 I'm not sure. It looked like from the logs that it did not compile with error nvidia-drm/nvidia-drm-fb.c:156:36: error: passing argument 1 of ‘drm_helper_mode_fill_fb_struct’ from incompatible pointer type

and I saw you were using 4.11 kernel from fedora 26. 

I wish/hope nvidia will fix it but am unsure of an ETA or the legality of patching it and making it available for download. Has something to do with this:

https://devtalk.nvidia.com/default/topic/995636/linux/-patches-378-13-4-10-and-4-10-stageing-/

**Comment by dje4321** [comment]
alright @gsgatlin 
ill see what a kernel downgrade does cause why not. got nothing to lose. If this doesnt work then i need to install fedora 25 in the mean time

**Comment by gsgatlin** [comment]
Hey, I see someone made a patch here:

https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-kmod.git/plain/kernel_4.11.patch

So you could see if that works in 4.11 kernel if you need to use that one.

**Comment by Brainiarc7** [comment]
Following up on that patch.
